name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set release info
        run: |
          echo "version=1" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d' --date='+9 hour')" >> $GITHUB_OUTPUT
        id: release-info
      - name: Create release
        uses: meta205/actions-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-name: ${{ steps.release-info.outputs.date }}
          release-name: v${{ steps.release-info.outputs.version }}
          body-path: ./docs/v${{ steps.release-info.outputs.version }}.md
          draft: true
