name: Create Project

on:
  workflow_dispatch:
    inputs:
      repo-name:
        required: true
        description: Please enter the repository name

jobs:
  create-project:
    runs-on: ubuntu-latest

    steps:
      - name: Create project repo
        uses: meta205/actions-create-repository@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-name: ${{ github.event.inputs.repo-name }}
          repo-private: false 
