name: Delete Package

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete package
        uses: meta205/actions-delete-package@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: kyongho2
          package-name: sandbox.sandbox
          package-version: 1.0.0
          package-type: maven
