name: Delete Package

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete package
        uses: meta205/actions-delete-package@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: zionex
          package-name: com.sap.sapjco
          package-version: 3.1.7
          package-type: maven
