name: Mail Sender
on:
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    env:
      product-name: 'Test Product'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get project version
        run: echo "version=1" >> $GITHUB_OUTPUT
        id: project
      - name: Get current date infos
        run: echo "date=$(date +'%Y-%m-%d' --date='+9 hour')" >> $GITHUB_OUTPUT
        id: date-infos
      - name: Replace release note
        run: |
          sed -i "s/:star: //g" ./docs/v${{ steps.project.outputs.version }}.md
          sed -i "s/:lady_beetle: //g" ./docs/v${{ steps.project.outputs.version }}.md
          sed -i "s/:notebook_with_decorative_cover: //g" ./docs/v${{ steps.project.outputs.version }}.md
          sed -i "s/:hammer: //g" ./docs/v${{ steps.project.outputs.version }}.md
          sed -i "s/:lock: //g" ./docs/v${{ steps.project.outputs.version }}.md
          echo -e "# ${{ env.product-name }} v${{ steps.project.outputs.version }} Release (${{ steps.date-infos.outputs.date }})\n" >> mail-header.md
          echo -e "${{ env.product-name }} 팀에서 ${{ env.product-name }} v${{ steps.project.outputs.version }} 버전을 릴리스합니다." >> mail-header.md
          cat mail-header.md ./docs/v${{ steps.project.outputs.version }}.md > mail-content.md
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[ Release ] ${{ env.product-name }} v${{ steps.project.outputs.version }} 버전 (Build ID : ${{ steps.date-infos.outputs.date }})"
          to: com,bluefish205@gmail.com
          from: Kyongho Lee <bluefish205@gmail.com>
          html_body: file://mail-content.md
          convert_markdown: true
          attachments: ./docs/v${{ steps.project.outputs.version }}.md
          priority: low
