name: Mail Sender
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date infos
        run: |
          echo "::set-output name=date1::$(date +'%Y-%m-%d' --date='+1 day')"
          echo "::set-output name=date2::$(date +'%Y%m%d' --date='+1 day')"
        id: date-infos
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.google.com
          account: ${{ secrets.MAIL_ADDRESS }}
          password: ${{ secrets.MAIL_PASSWORD }}
          sender: Zionex Release
          from: ${{ secrets.MAIL_ADDRESS }}
          subject: "[ Release ] T3SmartSCM 3.2.0 버전 (Build ID : ${{ steps.date-infos.outputs.date1 }})"
          body: file://docs/v22.0.0.md
          attachments: file://docs/v22.0.0.md
          to: kyongho_lee@zionex.com
