name: Mail Sender
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date infos
        run: |
          echo "date1=$(date +'%Y-%m-%d' --date='+9 hour')" >> $GITHUB_OUTPUT
          echo "date2=$(date +'%Y%m%d' --date='+9 hour')" >> $GITHUB_OUTPUT
        id: date-infos
      - name: Replace release note
        env:
          GITHUB_EMOJI_PATH: 'https\:\/\/github.githubassets.com\/images\/icons\/emoji\/unicode'
        run: |
          sed -i "s/:star:/\!\[star\]\($GITHUB_EMOJI_PATH\/2b50.png\)/g" ./docs/v22.1.0.md
          sed -i "s/:lady_beetle:/\!\[lady_beetle\]\($GITHUB_EMOJI_PATH\/1f41e.png\)/g" ./docs/v22.1.0.md
          sed -i "s/:notebook_with_decorative_cover:/\!\[notebook_with_decorative_cover\]\($GITHUB_EMOJI_PATH\/1f4d4.png\)/g" ./docs/v22.1.0.md
          sed -i "s/:hammer:/\!\[hammer\]\($GITHUB_EMOJI_PATH\/1f528.png\)/g" ./docs/v22.1.0.md
          sed -i "s/:lock:/\!\[lock\]\($GITHUB_EMOJI_PATH\/1f512.png\)/g" ./docs/v22.1.0.md
          cat ./docs/v22.1.0.md
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[ Release ] T3SmartSCM v22.1.0 버전 (Build ID : ${{ steps.date-infos.outputs.date1 }})"
          to: kyongho_lee@zionex.com,bluefish205@gmail.com
          from: Kyongho Lee <kyongho_lee@zionex.com>
          html_body: file://docs/v22.1.0.md
          convert_markdown: true
          attachments: ./docs/v22.1.0.md
          priority: low
