name: Mail Sender
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date infos
        run: |
          echo "date1=$(date +'%Y-%m-%d' --date='+9 hour')" >> $GITHUB_OUTPUT
          echo "date2=$(date +'%Y%m%d' --date='+9 hour')" >> $GITHUB_OUTPUT
        id: date-infos
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[ Release ] T3SmartSCM v22.1.0 버전 (Build ID : ${{ steps.date-infos.outputs.date1 }})"
          to: kyongho_lee@zionex.com,bluefish205@gmail.com
          from: Kyongho Lee <kyongho_lee@zionex.com>
          html_body: file://docs/v22.0.0.md
          convert_markdown: true
          attachments: ./docs/v22.0.0.md
          priority: low
