name: Mail Sender
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date infos
        run: echo "date=$(date +'%Y-%m-%d' --date='+9 hour')" >> $GITHUB_OUTPUT
        id: date-infos
      - name: Replace release note
        env:
          VERSION: '22.1.0'
        run: |
          sed -i "1s/^/T3SmartSCM팀에서 T3SmartSCM v$VERSION 버전을 릴리스합니다.\n\[Release Note Link\]\(https\:\/\/github.com\/zionex\/t3series\/releases\)\n\[Download Link\]\(https\:\/\/release.zionex.com\/T3SmartSCM\/v22.1.0\/\)/" ./docs/v$VERSION.md
          sed -i "s/:star://g" ./docs/v$VERSION.md
          sed -i "s/:lady_beetle://g" ./docs/v$VERSION.md
          sed -i "s/:notebook_with_decorative_cover://g" ./docs/v$VERSION.md
          sed -i "s/:hammer://g" ./docs/v$VERSION.md
          sed -i "s/:lock://g" ./docs/v$VERSION.md
          cat ./docs/v$VERSION.md
      - name: Send mail
        env:
          VERSION: '22.1.0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[ Release ] T3SmartSCM v$VERSION 버전 (Build ID : ${{ steps.date-infos.outputs.date }})"
          to: kyongho_lee@zionex.com,bluefish205@gmail.com
          from: Kyongho Lee <kyongho_lee@zionex.com>
          html_body: file://docs/v$VERSION.md
          convert_markdown: true
          attachments: ./docs/v$VERSION.md
          priority: low
